/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-12-07 16:30:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.Iterator;
import net.blog.bean.*;
import net.blog.dao.*;
import net.blog.db.DbCon;

public final class userhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
 
	String username = (String) session.getAttribute("login_name");
	String password = (String) session.getAttribute("login_password");

	System.out.println("session login_name => " + username);
	System.out.println("session login_password => " + password);

	
	Connection con = DbCon.getDbConn();
	Statement stmt = con.createStatement();
	String query = "select * from user where user_name='"
			+ username + "' and user_pwd = '" + password + "'";
	System.out.println(query);
	ResultSet rs = stmt.executeQuery(query);
	if (rs.next()) {
		System.out.println("valid user check in userhome");
	} else {
		System.out.println("failed to pass check userhome ... unvalid user");
		response.sendRedirect("login_fail.jsp");
	}
	rs.close();
	stmt.close();
	con.close();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><p><a href=\"userhome.jsp\">HOME</a></p></td>\r\n");
      out.write("\t\t<td> <p> </p> </td>\r\n");
      out.write("\t\t<td><p><a href=\"/Blog/diarydo?param=listDiary\">DARIY</a></p></td>\r\n");
      out.write("\t\t<td> <p> </p> </td>\r\n");
      out.write("\t\t<td><p><a href=\"/Blog/time_line.jsp\">TIMELINE</a></p></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr><td>\r\n");
      out.write("\t\t<form method=\"post\" action=\"/Blog/weibodo?param=addWeibo\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<input id=\"weibo_text\" type=\"text\" name=\"weibo_text\" size=\"50\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<input id=\"weibo_text_submit\" type=\"submit\" value=\"发微\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<form method=\"post\" action=\"/Blog/write_diary.jsp \" >\r\n");
      out.write("\t\t<input id=\"addFriend\" type=\"submit\" value=\"写日志\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<form method=\"post\" action=\"/Blog/userdo?param=addFriend \" >\r\n");
      out.write("\t\t<input id=\"addFriend\" type=\"submit\" value=\"加好友\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<form method=\"post\" action=\"/Blog/userdo?param=listFriend\" >\r\n");
      out.write("\t\t<input id=\"listFriend\" type=\"submit\" value=\"好友列表\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

		WeiboDao wd = new WeiboDao();
		ArrayList<Weibo> wl = wd.getWeiboByUser(username);
		Iterator<Weibo> its = wl.iterator();
		while (its.hasNext()) {
			Weibo it = (Weibo) its.next();
	
      out.write("\r\n");
      out.write("\t<tr><td>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><p>");
      out.print(it.getUser_name());
      out.write(" 说：</p></td>\r\n");
      out.write("\t\t\t<td><strong><p>");
      out.print(it.getText());
      out.write("</p></strong></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<form method=\"post\" action=\"/Blog/weibodo?param=delWeibo\">\r\n");
      out.write("\t\t");
      out.print("<input id=\"wei" + it.getId() + "\" type=\"hidden\" name=\"weibo_id\" " + "value=\""+ it.getId()+"\">");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print("<input id=\"submit_" + it.getId() + "\" type=\"submit\" name=\"weibo_id\" " + "value=\"删除\">");
      out.write("</td>\r\n");
      out.write("\t\t\t<td><p>");
      out.print(it.getDate());
      out.write("</p></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");

			CommDao cd = new CommDao();
			ArrayList<Comm> cl = cd.getCommByWeibo(Integer.parseInt(it.getId()));
			Iterator<Comm> xits = cl.iterator();
			while (xits.hasNext()) {
				Comm xit = (Comm) xits.next();
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><p>");
      out.print( xit.getName());
      out.write(" 评论：</p></td>\r\n");
      out.write("\t\t\t<td>");
      out.print( xit.getText() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t<form method=\"post\" action=\"/Blog/weibodo?param=addComm\">\r\n");
      out.write("\t\t");
      out.print("<input id=\"weic" + it.getId() + "\" type=\"hidden\" name=\"weiboc_id\" " + "value=\""+ it.getId()+"\">");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print("<input id=\"submit_" + it.getId() + "\" type=\"submit\" name=\"comm_id\" " + "value=\"评论\">");
      out.write("</td>\r\n");
      out.write("\t\t\t<td><textarea name=\"comment_text\"></textarea></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
